openapi: 3.0.0
info:
  title: Space Share API
  version: 1.0.0
  description: Space Share API
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
servers:
  - url: https://api.nasa.gov
    description: NASA API server
paths:
  "/planetary/apod":
    $ref: "./paths/nasa/apod.yml"
components:
  schemas:
    $ref: "./components/schemas/index.yml"
  parameters:
    $ref: "./components/parameters/index.yml"
  responses:
    $ref: "./components/responses/index.yml"
  securitySchemes:
    $ref: "./components/security/index.yml"
