/* tslint:disable */
/* eslint-disable */
/**
 * Space Share API
 * Space Share API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from './configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from './common';
import type { RequestArgs } from './base';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, BaseAPI, RequiredError, operationServerMap } from './base';

/**
 * 
 * @export
 * @interface APODResponse
 */
export interface APODResponse {
    /**
     * APOD画像の日付
     * @type {string}
     * @memberof APODResponse
     */
    'date'?: string;
    /**
     * APOD画像の説明
     * @type {string}
     * @memberof APODResponse
     */
    'explanation'?: string;
    /**
     * APOD画像のURL
     * @type {string}
     * @memberof APODResponse
     */
    'url'?: string;
    /**
     * 高解像度APOD画像のURL
     * @type {string}
     * @memberof APODResponse
     */
    'hdurl'?: string;
    /**
     * メディアの種類（画像またはビデオ）
     * @type {string}
     * @memberof APODResponse
     */
    'media_type'?: string;
    /**
     * サービスのバージョン
     * @type {string}
     * @memberof APODResponse
     */
    'service_version'?: string;
    /**
     * APOD画像のタイトル
     * @type {string}
     * @memberof APODResponse
     */
    'title'?: string;
    /**
     * APOD画像の著作権情報（利用可能な場合）
     * @type {string}
     * @memberof APODResponse
     */
    'copyright'?: string;
}
/**
 * 
 * @export
 * @interface NASABadResponse
 */
export interface NASABadResponse {
    /**
     * 
     * @type {number}
     * @memberof NASABadResponse
     */
    'code'?: number;
    /**
     * 
     * @type {string}
     * @memberof NASABadResponse
     */
    'msg'?: string;
    /**
     * 
     * @type {string}
     * @memberof NASABadResponse
     */
    'service_version'?: string;
}

/**
 * APODApi - axios parameter creator
 * @export
 */
export const APODApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 天文学の画像日報（APOD）を取得します。
         * @summary 天文学の画像日報
         * @param {string} [date] 取得したいAPOD画像の日付
         * @param {string} [startDate] 日付範囲の開始日。日付範囲でのデータを要求する場合に使用。&#x60;date&#x60;と一緒に使用できません。
         * @param {string} [endDate] 日付範囲の終了日。&#x60;start_date&#x60;と一緒に使用。
         * @param {number} [count] 指定した場合、ランダムに選ばれた&#x60;count&#x60;数の画像が返されます。&#x60;date&#x60;または&#x60;start_date&#x60;と&#x60;end_date&#x60;と一緒に使用できません。
         * @param {boolean} [thumbs] ビデオのサムネイルのURLを返します。APODがビデオでない場合、このパラメータは無視されます。
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getApod: async (date?: string, startDate?: string, endDate?: string, count?: number, thumbs?: boolean, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/planetary/apod`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication apiKeyAuth required
            await setApiKeyToObject(localVarQueryParameter, "api_key", configuration)

            if (date !== undefined) {
                localVarQueryParameter['date'] = (date as any instanceof Date) ?
                    (date as any).toISOString().substring(0,10) :
                    date;
            }

            if (startDate !== undefined) {
                localVarQueryParameter['start_date'] = (startDate as any instanceof Date) ?
                    (startDate as any).toISOString().substring(0,10) :
                    startDate;
            }

            if (endDate !== undefined) {
                localVarQueryParameter['end_date'] = (endDate as any instanceof Date) ?
                    (endDate as any).toISOString().substring(0,10) :
                    endDate;
            }

            if (count !== undefined) {
                localVarQueryParameter['count'] = count;
            }

            if (thumbs !== undefined) {
                localVarQueryParameter['thumbs'] = thumbs;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * APODApi - functional programming interface
 * @export
 */
export const APODApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = APODApiAxiosParamCreator(configuration)
    return {
        /**
         * 天文学の画像日報（APOD）を取得します。
         * @summary 天文学の画像日報
         * @param {string} [date] 取得したいAPOD画像の日付
         * @param {string} [startDate] 日付範囲の開始日。日付範囲でのデータを要求する場合に使用。&#x60;date&#x60;と一緒に使用できません。
         * @param {string} [endDate] 日付範囲の終了日。&#x60;start_date&#x60;と一緒に使用。
         * @param {number} [count] 指定した場合、ランダムに選ばれた&#x60;count&#x60;数の画像が返されます。&#x60;date&#x60;または&#x60;start_date&#x60;と&#x60;end_date&#x60;と一緒に使用できません。
         * @param {boolean} [thumbs] ビデオのサムネイルのURLを返します。APODがビデオでない場合、このパラメータは無視されます。
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getApod(date?: string, startDate?: string, endDate?: string, count?: number, thumbs?: boolean, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<APODResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getApod(date, startDate, endDate, count, thumbs, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['APODApi.getApod']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * APODApi - factory interface
 * @export
 */
export const APODApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = APODApiFp(configuration)
    return {
        /**
         * 天文学の画像日報（APOD）を取得します。
         * @summary 天文学の画像日報
         * @param {string} [date] 取得したいAPOD画像の日付
         * @param {string} [startDate] 日付範囲の開始日。日付範囲でのデータを要求する場合に使用。&#x60;date&#x60;と一緒に使用できません。
         * @param {string} [endDate] 日付範囲の終了日。&#x60;start_date&#x60;と一緒に使用。
         * @param {number} [count] 指定した場合、ランダムに選ばれた&#x60;count&#x60;数の画像が返されます。&#x60;date&#x60;または&#x60;start_date&#x60;と&#x60;end_date&#x60;と一緒に使用できません。
         * @param {boolean} [thumbs] ビデオのサムネイルのURLを返します。APODがビデオでない場合、このパラメータは無視されます。
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getApod(date?: string, startDate?: string, endDate?: string, count?: number, thumbs?: boolean, options?: any): AxiosPromise<APODResponse> {
            return localVarFp.getApod(date, startDate, endDate, count, thumbs, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * APODApi - object-oriented interface
 * @export
 * @class APODApi
 * @extends {BaseAPI}
 */
export class APODApi extends BaseAPI {
    /**
     * 天文学の画像日報（APOD）を取得します。
     * @summary 天文学の画像日報
     * @param {string} [date] 取得したいAPOD画像の日付
     * @param {string} [startDate] 日付範囲の開始日。日付範囲でのデータを要求する場合に使用。&#x60;date&#x60;と一緒に使用できません。
     * @param {string} [endDate] 日付範囲の終了日。&#x60;start_date&#x60;と一緒に使用。
     * @param {number} [count] 指定した場合、ランダムに選ばれた&#x60;count&#x60;数の画像が返されます。&#x60;date&#x60;または&#x60;start_date&#x60;と&#x60;end_date&#x60;と一緒に使用できません。
     * @param {boolean} [thumbs] ビデオのサムネイルのURLを返します。APODがビデオでない場合、このパラメータは無視されます。
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof APODApi
     */
    public getApod(date?: string, startDate?: string, endDate?: string, count?: number, thumbs?: boolean, options?: RawAxiosRequestConfig) {
        return APODApiFp(this.configuration).getApod(date, startDate, endDate, count, thumbs, options).then((request) => request(this.axios, this.basePath));
    }
}



